### ISSUE TITLE
java wrapper for halo 5

### ISSUE THREAD

**Issue by Gl4di4torRr** [GRosay/PHP-HaloAPI#4]
can we also extend this for java developer. That is, make a java wrapper?

**Comment by GRosay** [comment]
Maybe you should ask for it on the official API Forum. My wrapper is only for PHP; I don't manage the official API :)

Take a look here:
https://www.halowaypoint.com/en-us/forums/01b3ca58f06c4bd4ad074d8794d2cf86/topics

**Comment by Gl4di4torRr** [comment]
https://www.halowaypoint.com/en-us/forums/01b3ca58f06c4bd4ad074d8794d2cf86/topics/halo-5-java-wrapper/b93424a5-f5aa-43c0-b59e-6e523cf6e45f/posts

I actually did ask on their about this too. The forum is kinda slow... Thanks though!
