### ISSUE TITLE
missing argument sSessionId

### ISSUE THREAD

**Issue by paradox1029** [GRosay/PHP-HaloAPI#6]
[**haloapi.class.php** v1.0.3-beta]
using the example in **example.php**:
`$oJson = $oHaloApi->getServiceRecords("campaign"); // Get service records for campaign`

you get the warning:

> **Warning**: Missing argument 2 for haloapi::getServiceRecords(), called in **.../public_html/index.php** on line 26 and defined in **.../public_html/HaloAPI-master/haloapi.class.php** on line 601

I saw in **haloapi.class.php** in the _getServiceRecords(...)_ function
`if(!is_null($sSeasonId)){ ... }`

<br/>
I found the easy fix for this warning is make argument 2 = **null** in **haloapi.class.php**:
**_Before_**:
`public function getServiceRecords($sMatchType, $sSeasonId){ ... }`
**_After_**:
`public function getServiceRecords($sMatchType, $sSeasonId = null){ ... }`
so if they dont put argument 2 its already **null** so they dont have to specify it to be **null**

**Comment by GRosay** [comment]
Thanks for sharing the issue.
I'm busy those days but I'll correct it right now !
